# app.py

import io
import json
import math
import os

import soundfile as sf
import torch
import torch.nn.functional as F
from flask import Flask, Request, request, jsonify
from pathlib import Path
from werkzeug.formparser import FormDataParser

# The architecture and the preprocessing come from model.py, the same module the
# trainer uses. Never redefine them here — that is how train/serve drift starts.
from model import (
    CLASS_NAMES,
    DEFAULT_ARCH,
    DEFAULT_FRONTEND,
    N_LFCC,
    MAX_LEN,
    N_MELS,
    SAMPLE_RATE,
    build_model,
    build_transform,
    load_audio,
    preprocess_waveform,
)

# ===================================================================
# 1. LOAD THE TRAINED MODEL FROM THE SAVED FILE
# ===================================================================
SCRIPT_DIR = Path(__file__).resolve().parent

# train_dp_avspoof.py writes checkpoints/best.pth (selected by dev EER). The
# legacy flat file is kept as a fallback for older runs.
#
# $CKPT_ROOT must name the same directory the trainer wrote to — it reads the
# same variable. Set it when the checkpoint tree lives outside the repo, which
# is the normal case for anything trained on the cluster and copied back.
CKPT_DIR = Path(os.getenv("CKPT_ROOT", SCRIPT_DIR / "checkpoints"))
BEST_CKPT = CKPT_DIR / "best.pth"
LEGACY_MODEL_PATH = SCRIPT_DIR / "deepfake_audio_detector.pth"


# The fallback operating point, used only when the checkpoint carries no
# calibrated threshold (legacy weights, or a run that predates save_ckpt
# storing it). 0.5 is argmax, which is rarely right on 1:9 data — the response
# reports which of the two the client got, so a UI can say so.
DEFAULT_THRESHOLD = 0.5

# How the model card names each input degradation (model.DEGRADATIONS). "none"
# is omitted from the card rather than shown as a row saying nothing happened.
DEGRADATION_NAMES = {
    "none": None,
    "opus": "Every clip passed through the Opus voice codec first",
    "tel8k": "Every clip limited to phone-line bandwidth (4 kHz) first",
    "noise20": "Fixed background noise added to every clip first (20 dB SNR)",
}


def load_model():
    if BEST_CKPT.exists():
        path = BEST_CKPT
    elif LEGACY_MODEL_PATH.exists():
        path = LEGACY_MODEL_PATH
    else:
        raise FileNotFoundError(
            f"No trained weights found. Looked for {BEST_CKPT} and {LEGACY_MODEL_PATH}.\n"
            f"Run:  python train_dp_avspoof.py --corpus LA"
        )

    # weights_only=False, matching evaluate.py and the trainer's resume path.
    # torch 2.6 flipped this default to True, which refuses any checkpoint
    # containing a non-tensor object — and ours do: Opacus's get_epsilon()
    # returns a numpy scalar, so every DP checkpoint carries one inside
    # `metrics`. The failure is a raised UnpicklingError at import time, i.e.
    # the server will not start at all rather than serve something wrong.
    #
    # The flag does mean the pickle may execute code, so it is safe exactly to
    # the extent that best.pth is. That is an operator-placed deployment
    # artifact from our own training, not user input — the upload path never
    # reaches this call.
    payload = torch.load(path, map_location=torch.device("cpu"), weights_only=False)
    # Checkpoints from save_ckpt() are a dict with a "model" key; a bare
    # state_dict (the legacy file) is used as-is.
    state_dict = payload["model"] if isinstance(payload, dict) and "model" in payload else payload

    # Which network these weights describe. A bare legacy state_dict carries no
    # architecture, and everything that predates the field is the CNN.
    arch = (payload.get("arch") if isinstance(payload, dict) else None) or DEFAULT_ARCH

    net = build_model(arch)
    try:
        net.load_state_dict(state_dict)
    except RuntimeError as e:
        raise RuntimeError(
            f"Weights at {path} do not match the {arch!r} architecture in model.py. "
            f"They were trained with an older version and must be regenerated by "
            f"re-running train_dp_avspoof.py.\n\nOriginal error: {e}"
        )

    # Evaluation mode disables dropout — important for consistent predictions.
    net.eval()

    # The threshold the trainer calibrated from dev-set EER. It travels with the
    # weights because it belongs to them: a different run has a different
    # operating point, and pairing new weights with an old cutoff is silently
    # wrong in exactly the way an implicit 0.5 was.
    threshold = None
    if isinstance(payload, dict):
        threshold = payload.get("threshold")
    calibrated = threshold is not None
    if not calibrated:
        threshold = DEFAULT_THRESHOLD

    # What produced this reading, read off the checkpoint rather than written
    # down anywhere. The result page shows a model card, and a hand-maintained
    # one is worse than none: it looks like provenance while quietly describing
    # a run that no longer exists. Anything the checkpoint does not know is
    # omitted rather than guessed.
    metrics = (payload.get("metrics") or {}) if isinstance(payload, dict) else {}
    dp = payload.get("dp") if isinstance(payload, dict) else None

    # Which front-end these weights were trained on. Serving log-Mel features to
    # an LFCC-trained model produces confident nonsense rather than an error —
    # the adaptive pool accepts either shape — so this is read from the
    # checkpoint, never assumed. Checkpoints predating the choice are log-Mel.
    frontend = (payload.get("frontend") if isinstance(payload, dict) else None) or DEFAULT_FRONTEND

    # The input degradation calibrate.py fitted the threshold under
    # (model.degrade_waveform). Serving without it would compare clean inputs
    # against a line drawn for degraded ones.
    degradation = (payload.get("input_degradation") if isinstance(payload, dict) else None) or "none"

    # The representation and the network description are read off the
    # checkpoint for the same reason every other field here is: a hand-written
    # model card looks like provenance while describing whichever run someone
    # last remembered to type in.
    representations = {
        "logmel": f"Log-Mel spectrogram, {N_MELS} mels",
        "lfcc": f"LFCC, {N_LFCC} coefficients + Δ + ΔΔ",
        "raw": f"Raw waveform, learned band-pass filters",
    }
    networks = {
        "cnn": "2× conv, adaptive pool, 2 dense",
        "aasist": "SincConv, 6 residual blocks, spectro-temporal graph attention",
        "aasist-l": "SincConv, 6 residual blocks, spectro-temporal graph attention (light)",
        "ssl-aasist": "XLS-R 300M (wav2vec 2.0), spectro-temporal graph attention",
    }

    # SSL-AASIST reads the raw waveform too, but through XLS-R's convolutional
    # feature encoder, not AASIST's sinc filterbank.
    if arch == "ssl-aasist":
        representations["raw"] = "Raw waveform, XLS-R convolutional features"

    # --extra-train corpora join ASVspoof2019 in training; a card naming only
    # LA would misstate what the model has heard.
    extra_names = {"speechfake": "SpeechFake", "asvspoof5": "ASVspoof 5",
                   "synth": "own generated fakes (8 open TTS families)"}
    extra = (payload.get("extra_train") if isinstance(payload, dict) else None) or ""
    corpora = [f"ASVspoof2019 {metrics['corpus']}"] if metrics.get("corpus") else []
    corpora += [extra_names.get(e, e) for e in extra.split("+") if e]

    info = {
        "input": f"Mono, {SAMPLE_RATE // 1000} kHz, {MAX_LEN // SAMPLE_RATE} s",
        "representation": representations.get(frontend, frontend),
        "network": networks.get(arch, arch),
        "parameters": sum(p.numel() for p in net.parameters()),
        "input_processing": DEGRADATION_NAMES.get(degradation, degradation),
        "corpus": " + ".join(corpora) or None,
        "epoch": payload.get("epoch") if isinstance(payload, dict) else None,
        "dev_eer": metrics.get("dev_eer"),
        "privacy": (
            f"DP-SGD (Opacus), ε={metrics['epsilon']:.2f}, δ={metrics['delta']}"
            if dp and metrics.get("epsilon") is not None
            else "DP-SGD (Opacus)" if dp
            else "None — non-private baseline"
        ),
        # calibrate.py records where a recalibrated threshold came from; older
        # checkpoints carry the trainer's dev-EER threshold and say nothing.
        "threshold_source": (
            (payload.get("threshold_source") if isinstance(payload, dict) else None)
            or ("Equal error rate, dev partition" if calibrated else "Default 0.5, uncalibrated")
        ),
    }

    print(f"Loaded model weights from {path}")
    print(f"Decision threshold: {threshold:.4g} ({info['threshold_source']})")
    print(f"Architecture: {arch}, front-end: {frontend}, input degradation: {degradation}")
    calibration = (payload.get("calibration") or {}) if isinstance(payload, dict) else {}
    return net, float(threshold), calibrated, info, frontend, calibration, degradation


def logit(p):
    """P(spoof) -> log-odds, the scale evaluate.py scores and calibrates on."""
    p = min(max(float(p), 1e-12), 1 - 1e-12)
    return math.log(p) - math.log1p(-p)


model, THRESHOLD, THRESHOLD_CALIBRATED, MODEL_INFO, FRONTEND, CALIBRATION, DEGRADATION = load_model()

# ---------------------------------------------------------------------------
# The reading's scale. SSL-AASIST pushes P(spoof) to within a hair of 0 or 1
# (RESULTS.md Finding 8), and the served threshold is P = 0.99966 (Finding 12).
# On a 0-1 scale nearly every reading and the threshold share the last pixel,
# so the page draws the model's own score instead: the log-odds, i.e. the
# difference of the two logits, which is what every threshold here was fitted
# on. P(spoof) is still returned; it is the sigmoid of the score.
# ---------------------------------------------------------------------------
THRESHOLD_SCORE = CALIBRATION.get("threshold_log_odds")
if THRESHOLD_SCORE is None:
    THRESHOLD_SCORE = logit(THRESHOLD)

# The uncertain band's lower edge: the 95th percentile of the calibration
# set's CHECK half, which calibrate.py stores in the checkpoint. Genuine speech
# the threshold was not fitted to scores above it one time in twenty, so a
# reading between it and the threshold is not flagged but is not clear either.
# Read from held-out real speech only — never from In-the-Wild.
CALIBRATION_NAMES = {"peoples_speech": "People's Speech", "commonvoice": "Common Voice",
                     "voxpopuli": "VoxPopuli"}
UNCERTAIN_BAND = None
_p95 = (CALIBRATION.get("check_score_percentiles_log_odds") or {}).get("95")
if _p95 is not None and _p95 < THRESHOLD_SCORE:
    # calibrate.py records the set as e.g. "peoples_speech (en)".
    _set = (CALIBRATION.get("calibration_set") or "").split(" ")[0]
    UNCERTAIN_BAND = {
        "low": float(_p95),
        "source": f"95% of held-out {CALIBRATION_NAMES.get(_set, _set or 'calibration')} "
                  f"real clips score below this",
    }

# Error rates measured for exactly this checkpoint at exactly this threshold,
# from evaluate.py's JSON copied beside it as best.measured-<name>.json. A file
# measured at any other threshold describes a different operating point, so it
# is skipped rather than shown — the same reason the model card is read off the
# checkpoint rather than typed into the page.
MEASURED_SETS = {
    "itw": ("In-the-Wild", "Real-world recordings of public figures: interviews, "
                           "speeches, broadcasts, and deepfakes of the same people"),
    "asvspoof": ("ASVspoof2019 LA eval", "Clean studio speech; the fakes are 2019-era "
                                         "text-to-speech and voice conversion"),
    # A seen-generator test (RESULTS.md Finding 13): the model trained on these
    # 26 systems and on these real corpora, so it is the friendly case.
    "speechfake": ("SpeechFake test (English)", "Clean modern text-to-speech and voice "
                                                "cloning from 26 systems — all of which "
                                                "the model saw in training"),
    # Unseen-generator test (RESULTS.md Finding 18): our own fakes from four
    # open TTS families held out of training; LibriSpeech as the real side.
    "synth": ("Unseen open TTS (held-out families)", "Clean fakes from four open "
                                                     "text-to-speech families the model "
                                                     "never trained on"),
}


def load_measured():
    measured = []
    for f in sorted(CKPT_DIR.glob(f"{BEST_CKPT.stem}.measured-*.json")):
        try:
            report = json.loads(f.read_text())
            served = report["pooled"]["at_served_threshold"]
            c = served["confusion"]
        except (OSError, ValueError, KeyError, TypeError):
            print(f"Skipping {f.name}: not an evaluate.py report")
            continue
        if not math.isclose(served["threshold"], THRESHOLD, rel_tol=0, abs_tol=1e-9):
            print(f"Skipping {f.name}: measured at threshold {served['threshold']:.6g}, "
                  f"serving {THRESHOLD:.6g}")
            continue
        # Reports predating the field were all scored on unmodified inputs.
        if (report.get("input_degradation") or "none") != DEGRADATION:
            print(f"Skipping {f.name}: measured with input degradation "
                  f"{report.get('input_degradation') or 'none'}, serving {DEGRADATION}")
            continue
        name, about = MEASURED_SETS.get(report.get("dataset"), (report.get("corpus"), None))
        measured.append({
            "set": name,
            "about": about,
            "real_flagged": c["fp"] / (c["tn"] + c["fp"]),
            "fakes_passed": c["fn"] / (c["fn"] + c["tp"]),
            "n_real": c["tn"] + c["fp"],
            "n_fake": c["fn"] + c["tp"],
        })
    return measured


MEASURED = load_measured()
print(f"Threshold score: {THRESHOLD_SCORE:+.2f}; uncertain band from "
      f"{UNCERTAIN_BAND['low']:+.2f}" if UNCERTAIN_BAND else
      f"Threshold score: {THRESHOLD_SCORE:+.2f}; no uncertain band in this checkpoint")
print(f"Measured error rates: {', '.join(m['set'] for m in MEASURED) or 'none'}")


def reading_context():
    """Everything a reading is interpreted against, shared by /health and /predict."""
    return {
        "threshold": THRESHOLD,
        "threshold_score": THRESHOLD_SCORE,
        "threshold_calibrated": THRESHOLD_CALIBRATED,
        "uncertain_band": UNCERTAIN_BAND,
        "measured": MEASURED,
        "model": MODEL_INFO,
    }
transform_pipeline = build_transform(FRONTEND)

# ===================================================================
# 2. PREPROCESS A SINGLE AUDIO FILE
# ===================================================================
def preprocess_audio(audio_file):
    waveform, sample_rate = load_audio(audio_file)
    spectrogram = preprocess_waveform(waveform, sample_rate, transform_pipeline,
                                      degradation=DEGRADATION)
    # Add a "batch" dimension for the model
    return spectrogram.unsqueeze(0)

# ===================================================================
# 3. CREATE THE FLASK WEB SERVER
# ===================================================================
app = Flask(__name__)

# Matches MAX_BYTES in src/app/upload/page.js. Flask has no default cap, so
# without this a large upload is read into memory in full before anything looks
# at it. Werkzeug raises 413 past this point; the handler below makes that JSON
# rather than an HTML error page the frontend cannot parse.
MAX_UPLOAD_BYTES = 5 * 1024 * 1024
app.config["MAX_CONTENT_LENGTH"] = MAX_UPLOAD_BYTES


# ---------------------------------------------------------------------------
# Keep the uploaded clip out of the filesystem. This is the project's central
# privacy claim, and by default it was false.
#
# Werkzeug's default stream factory hands each uploaded file a
# SpooledTemporaryFile with max_size = 1024 * 500. Under 500 KB the upload
# stays in a BytesIO; over it, the spool rolls over and the bytes are written
# to the filesystem behind $TMPDIR. Measured here: a 2 MB upload rolls over to
# /tmp on an ext4-family filesystem — a real block device, not tmpfs — so a
# user's voice lands on physical storage.
#
# The mitigations that do apply are real but partial. The file is created
# unlinked (nlink=0), so it has no name another user can find in a directory
# listing, and it is released when the request ends. But the bytes still reach
# the disk, they are readable through /proc/<pid>/fd by root or the same uid
# while the request is in flight, they can outlive the process in free blocks
# until overwritten, and on a machine with swap they can reach swap too.
#
# Forcing BytesIO is safe *because* MAX_CONTENT_LENGTH above caps the request
# at 5 MB — that cap is what makes an unconditional in-memory buffer bounded,
# so the two settings must move together. Raise the limit and this becomes a
# memory-exhaustion vector.
#
# This is the guarantee DP-SGD does not provide and cannot: differential
# privacy protects the *training* corpus, which is public. The clip a user
# uploads is an inference-time concern, and this is where it is answered.
# See "Differential privacy: off now, ready later" in APPROACH.md.
# ---------------------------------------------------------------------------
class InMemoryFormDataParser(FormDataParser):
    def __init__(self, *args, **kwargs):
        kwargs["stream_factory"] = lambda *a, **k: io.BytesIO()
        super().__init__(*args, **kwargs)


class InMemoryRequest(Request):
    form_data_parser_class = InMemoryFormDataParser


app.request_class = InMemoryRequest


@app.errorhandler(413)
def too_large(_):
    return jsonify({"error": f"Audio file exceeds the {MAX_UPLOAD_BYTES // (1024 * 1024)} MB limit."}), 413


@app.route("/health", methods=["GET"])
def health():
    """Enough for the proxy route to report the model server being down as a
    connection problem rather than a failed analysis."""
    return jsonify({"status": "ok", **reading_context()})

@app.route("/predict", methods=["POST"])
def predict():
    # Check if a file was sent in the request
    if 'file' not in request.files:
        return jsonify({"error": "No audio file provided"}), 400

    audio_file = request.files['file']

    try:
        # 1. Preprocess the incoming audio file. It never reaches the
        #    filesystem — see InMemoryRequest above, which is what makes that
        #    true rather than merely hoped for — and the tensor is all that
        #    survives this call.
        tensor = preprocess_audio(audio_file)

        # 2. Make a prediction (no gradients needed)
        with torch.no_grad():
            outputs = model(tensor)
            probabilities = F.softmax(outputs, dim=1)
            spoof_probability = probabilities[0][1].item()   # class 1 = spoof
            # The logit difference: log-odds of spoof, unsaturated. The label
            # is decided on it too, so it agrees with evaluate.py to the bit.
            spoof_score = (outputs[0][1] - outputs[0][0]).item()

        # 3. Send the result back as JSON.
        #
        #    P(spoof) rather than "the winning class and its confidence": the UI
        #    grades the reading into bands and draws it on a scale, which needs a
        #    continuous value. `Real Audio, 90%` means P(spoof)=10%, and a client
        #    can only recover that by unpacking the label — a conversion nobody
        #    should have to do twice. The threshold ships with it because the
        #    label is meaningless without the line it was compared against.
        return jsonify({
            "spoof_probability": spoof_probability,
            "spoof_score": spoof_score,
            "prediction": CLASS_NAMES[1 if spoof_score >= THRESHOLD_SCORE else 0],
            **reading_context(),
        })
    except sf.LibsndfileError as e:
        # A file libsndfile cannot open. That is the client's problem, not a
        # server fault, and the message is written for the person who chose the
        # file rather than echoing the decoder — str(e) here includes the
        # internal FileStorage repr, which is both ugly and no one's business.
        # Deliberately not logging `e`: libsndfile's message embeds the
        # FileStorage repr, and with it the user's original filename. A
        # filename is user data — "interview_with_my_doctor.wav" says plenty —
        # and it has no place in a server log on a privacy-focused tool.
        print("[predict] could not decode upload (LibsndfileError)")
        return jsonify({
            "error": "That file could not be decoded as audio. It may be corrupt, "
                     "or in a format this server does not support."
        }), 422
    except Exception as e:
        # Genuinely unexpected. Logged in full here, reported as a generic
        # failure there: an exception string is an information leak and tells a
        # user nothing they can act on.
        print(f"[predict] unexpected failure: {type(e).__name__}: {e}")
        return jsonify({"error": "The clip could not be analysed."}), 500

if __name__ == "__main__":
    # debug=False: the reloader's interactive debugger executes arbitrary code
    # from the browser, and this port becomes reachable the moment the Next.js
    # proxy route starts calling it. Bound to loopback for the same reason —
    # nothing but the proxy should be able to reach the model.
    #
    # Still the Werkzeug development server. That is fine for a dev machine and
    # not fine for anything else; use waitress or gunicorn when this is hosted.
    print("Starting Flask server... Visit http://127.0.0.1:5000")
    app.run(host="127.0.0.1", port=5000, debug=False)