# app.py

import torch
import torchaudio
import torch.nn.functional as F
from flask import Flask, request, jsonify
from pathlib import Path

# The architecture and the preprocessing come from model.py, the same module the
# trainer uses. Never redefine them here — that is how train/serve drift starts.
from model import AudioClassifierCNN, CLASS_NAMES, build_transform, preprocess_waveform

# ===================================================================
# 1. LOAD THE TRAINED MODEL FROM THE SAVED FILE
# ===================================================================
SCRIPT_DIR = Path(__file__).resolve().parent

# train_dp_avspoof.py writes checkpoints/best.pth (selected by dev EER). The
# legacy flat file is kept as a fallback for older runs.
BEST_CKPT = SCRIPT_DIR / "checkpoints" / "best.pth"
LEGACY_MODEL_PATH = SCRIPT_DIR / "deepfake_audio_detector.pth"


def load_model():
    if BEST_CKPT.exists():
        path = BEST_CKPT
    elif LEGACY_MODEL_PATH.exists():
        path = LEGACY_MODEL_PATH
    else:
        raise FileNotFoundError(
            f"No trained weights found. Looked for {BEST_CKPT} and {LEGACY_MODEL_PATH}.\n"
            f"Run:  python train_dp_avspoof.py --corpus LA"
        )

    payload = torch.load(path, map_location=torch.device("cpu"))
    # Checkpoints from save_ckpt() are a dict with a "model" key; a bare
    # state_dict (the legacy file) is used as-is.
    state_dict = payload["model"] if isinstance(payload, dict) and "model" in payload else payload

    net = AudioClassifierCNN()
    try:
        net.load_state_dict(state_dict)
    except RuntimeError as e:
        raise RuntimeError(
            f"Weights at {path} do not match the current architecture in model.py. "
            f"They were trained with an older version and must be regenerated by "
            f"re-running train_dp_avspoof.py.\n\nOriginal error: {e}"
        )

    # Evaluation mode disables dropout — important for consistent predictions.
    net.eval()
    print(f"Loaded model weights from {path}")
    return net


model = load_model()
transform_pipeline = build_transform()

# ===================================================================
# 2. PREPROCESS A SINGLE AUDIO FILE
# ===================================================================
def preprocess_audio(audio_file):
    waveform, sample_rate = torchaudio.load(audio_file)
    spectrogram = preprocess_waveform(waveform, sample_rate, transform_pipeline)
    # Add a "batch" dimension for the model
    return spectrogram.unsqueeze(0)

# ===================================================================
# 3. CREATE THE FLASK WEB SERVER
# ===================================================================
app = Flask(__name__)

@app.route("/predict", methods=["POST"])
def predict():
    # Check if a file was sent in the request
    if 'file' not in request.files:
        return jsonify({"error": "No audio file provided"}), 400

    audio_file = request.files['file']
    
    try:
        # 1. Preprocess the incoming audio file
        tensor = preprocess_audio(audio_file)
        
        # 2. Make a prediction (no gradients needed)
        with torch.no_grad():
            outputs = model(tensor)
            # Get the predicted class index (0 or 1)
            _, predicted_idx = torch.max(outputs.data, 1)
            predicted_label = CLASS_NAMES[predicted_idx.item()]
            
            # 3. Calculate the confidence score
            probabilities = F.softmax(outputs, dim=1)
            confidence = probabilities[0][predicted_idx.item()].item()

        # 4. Send the result back as JSON
        return jsonify({
            "prediction": predicted_label,
            "confidence": f"{confidence:.2%}"
        })
    except Exception as e:
        return jsonify({"error": str(e)}), 500

if __name__ == "__main__":
    # Start the server
    print("Starting Flask server... Visit http://127.0.0.1:5000")
    app.run(debug=True)