"""Writes src/lib/samples.json: the home page's sample readings.

The hero shows the two sample clips (LA_T_*.flac) as they were actually
scored by the served model, with their waveform envelope. Nothing on that
panel is typed in by hand — rerun this after a new checkpoint is served:

    MODEL_API_URL=https://... MODEL_API_TOKEN=... ../venv/bin/python sample_readings.py

It also copies the clips to public/samples/ so the page can play them.
"""

import datetime
import json
import os
import shutil
from pathlib import Path

import numpy as np
import requests
import soundfile as sf

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
API = os.environ.get("MODEL_API_URL", "http://127.0.0.1:5000").rstrip("/")
TOKEN = os.environ.get("MODEL_API_TOKEN")

# ASVspoof2019 LA train labels, from train_file.txt.
CLIPS = [
    ("LA_T_1000137", "spoof", "Synthetic speech"),
    ("LA_T_1000406", "bonafide", "Real recording"),
]
BARS = 64
WINDOW = 64000  # the model reads the first 4 s at 16 kHz


def envelope(path):
    """RMS per bar over the clip's own length, normalised, square-rooted so
    quiet syllables stay visible. Rounded: it is a picture, not a measurement."""
    audio, rate = sf.read(path, dtype="float32", always_2d=True)
    mono = audio.mean(axis=1)
    rms = np.array([np.sqrt(np.mean(s ** 2)) for s in np.array_split(mono, BARS)])
    rms = np.sqrt(rms / rms.max())
    return [round(float(v), 3) for v in rms], len(mono) / rate


def main():
    headers = {"Authorization": f"Bearer {TOKEN}"} if TOKEN else {}
    out_dir = ROOT / "public" / "samples"
    out_dir.mkdir(parents=True, exist_ok=True)
    samples = []
    threshold = band_low = None
    for clip_id, label, title in CLIPS:
        path = HERE / f"{clip_id}.flac"
        with open(path, "rb") as f:
            r = requests.post(f"{API}/predict", files={"file": f}, headers=headers, timeout=300)
        r.raise_for_status()
        reading = r.json()
        threshold = reading["threshold_score"]
        band_low = (reading.get("uncertain_band") or {}).get("low")
        peaks, seconds = envelope(path)
        shutil.copy(path, out_dir / path.name)
        samples.append({
            "id": clip_id,
            "label": label,
            "title": title,
            "src": f"/samples/{path.name}",
            "seconds": round(seconds, 2),
            "score": round(reading["spoof_score"], 3),
            "peaks": peaks,
        })
        print(f"{clip_id} ({label}): score {reading['spoof_score']:+.3f}")

    data = {
        "_about": "Generated by ai_model/sample_readings.py from the served model. Do not edit by hand.",
        "scored": datetime.date.today().isoformat(),
        "source": "ASVspoof 2019 LA (train), ODC-By 1.0",
        "threshold": round(threshold, 3),
        "bandLow": round(band_low, 3) if band_low is not None else None,
        "samples": samples,
    }
    dest = ROOT / "src" / "lib" / "samples.json"
    dest.write_text(json.dumps(data, indent=2) + "\n")
    print(f"wrote {dest.relative_to(ROOT)}; threshold {threshold:+.3f}")


if __name__ == "__main__":
    main()
